

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1246, 858)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1261, 901))
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Prva_analiza = QtWidgets.QWidget()
        self.Prva_analiza.setObjectName("Prva_analiza")
        self.pushButton = QtWidgets.QPushButton(self.Prva_analiza)
        self.pushButton.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(self.Prva_analiza)
        self.pushButton_6.setGeometry(QtCore.QRect(980, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.Prva_analiza)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.Prva_analiza)
        self.pushButton_9.setGeometry(QtCore.QRect(850, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.Prva_analiza)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_12 = QtWidgets.QPushButton(self.Prva_analiza)
        self.pushButton_12.setGeometry(QtCore.QRect(1110, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.textBrowser = QtWidgets.QTextBrowser(self.Prva_analiza)
        self.textBrowser.setGeometry(QtCore.QRect(10, 50, 1231, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.label_67 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_67.setGeometry(QtCore.QRect(110, 600, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.label_6 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_6.setGeometry(QtCore.QRect(110, 470, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_11.setGeometry(QtCore.QRect(10, 280, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_30 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_30.setGeometry(QtCore.QRect(240, 290, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 490, 91, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 250, 191, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_32 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_32.setGeometry(QtCore.QRect(240, 600, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_36 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_36.setGeometry(QtCore.QRect(330, 470, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_22.setGeometry(QtCore.QRect(330, 350, 81, 31))
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_35 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_35.setGeometry(QtCore.QRect(330, 600, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_16.setGeometry(QtCore.QRect(330, 490, 81, 31))
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_17.setGeometry(QtCore.QRect(240, 550, 81, 31))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_7 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_7.setGeometry(QtCore.QRect(10, 600, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_23.setGeometry(QtCore.QRect(110, 620, 91, 31))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_18.setGeometry(QtCore.QRect(330, 550, 81, 31))
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 620, 91, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_8.setGeometry(QtCore.QRect(240, 490, 81, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_15.setGeometry(QtCore.QRect(330, 620, 81, 31))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_13 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_13.setGeometry(QtCore.QRect(110, 330, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_2.setGeometry(QtCore.QRect(10, 470, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_4.setGeometry(QtCore.QRect(10, 380, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_20.setGeometry(QtCore.QRect(240, 350, 81, 31))
        self.lineEdit_20.setStyleSheet("")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_34 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_34.setGeometry(QtCore.QRect(110, 530, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_37 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_37.setGeometry(QtCore.QRect(240, 530, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.pushButton_7 = QtWidgets.QPushButton(self.Prva_analiza)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 690, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_10 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_10.setGeometry(QtCore.QRect(10, 330, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 300, 91, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 490, 91, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_10.setGeometry(QtCore.QRect(240, 620, 81, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_31 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_31.setGeometry(QtCore.QRect(240, 470, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_14.setGeometry(QtCore.QRect(110, 550, 91, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_38 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_38.setGeometry(QtCore.QRect(330, 530, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_39.setGeometry(QtCore.QRect(330, 410, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 350, 91, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label = QtWidgets.QLabel(self.Prva_analiza)
        self.label.setGeometry(QtCore.QRect(10, 410, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_41 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_41.setGeometry(QtCore.QRect(240, 330, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_9.setGeometry(QtCore.QRect(110, 350, 91, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_19.setGeometry(QtCore.QRect(240, 430, 81, 31))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_5 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_5.setGeometry(QtCore.QRect(110, 410, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 550, 91, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_12 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_12.setGeometry(QtCore.QRect(10, 190, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton_5 = QtWidgets.QPushButton(self.Prva_analiza)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 760, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_33 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_33.setGeometry(QtCore.QRect(10, 220, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_12.setGeometry(QtCore.QRect(110, 300, 91, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_40 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_40.setGeometry(QtCore.QRect(240, 410, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.lineEdit = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit.setGeometry(QtCore.QRect(10, 430, 91, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 430, 91, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_42 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_42.setGeometry(QtCore.QRect(330, 330, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_9 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_9.setGeometry(QtCore.QRect(110, 280, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.Prva_analiza)
        self.label_3.setGeometry(QtCore.QRect(10, 530, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.Prva_analiza)
        self.lineEdit_21.setGeometry(QtCore.QRect(330, 430, 81, 31))
        self.lineEdit_21.setText("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.tabWidget = QtWidgets.QTabWidget(self.Prva_analiza)
        self.tabWidget.setGeometry(QtCore.QRect(420, 190, 831, 661))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWebEngineWidgets.QWebEngineView()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWebEngineWidgets.QWebEngineView()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWebEngineWidgets.QWebEngineView()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWebEngineWidgets.QWebEngineView()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWebEngineWidgets.QWebEngineView()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.stackedWidget.addWidget(self.Prva_analiza)
        self.Home = QtWidgets.QWidget()
        self.Home.setStyleSheet("")
        self.Home.setObjectName("Home")
        self.pushButton_23 = QtWidgets.QPushButton(self.Home)
        self.pushButton_23.setGeometry(QtCore.QRect(840, 440, 221, 201))
        self.pushButton_23.setStyleSheet("QPushButton\n"
"{\n"
"border-radius: 20px;\n"
"background-color: white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  border: 5px solid;\n"
"\n"
"\n"
"}")
        self.pushButton_23.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/slike5/3_gumb.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_23.setIcon(icon)
        self.pushButton_23.setIconSize(QtCore.QSize(210, 210))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_26 = QtWidgets.QPushButton(self.Home)
        self.pushButton_26.setGeometry(QtCore.QRect(1120, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.Home)
        self.pushButton_27.setGeometry(QtCore.QRect(990, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_29 = QtWidgets.QPushButton(self.Home)
        self.pushButton_29.setGeometry(QtCore.QRect(520, 440, 231, 201))
        self.pushButton_29.setStyleSheet("QPushButton\n"
"{\n"
"border-radius: 20px;\n"
"background-color: white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  border: 5px solid;\n"
"\n"
"\n"
"}")
        self.pushButton_29.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/slike3/2_gumb.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_29.setIcon(icon1)
        self.pushButton_29.setIconSize(QtCore.QSize(200, 200))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.Home)
        self.pushButton_30.setGeometry(QtCore.QRect(200, 440, 231, 201))
        self.pushButton_30.setAutoFillBackground(False)
        self.pushButton_30.setStyleSheet("QPushButton\n"
"{\n"
"border-radius: 20px;\n"
"background-color: white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  border: 5px solid;\n"
"\n"
"\n"
"}")
        self.pushButton_30.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/slike4/1_gumb.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_30.setIcon(icon2)
        self.pushButton_30.setIconSize(QtCore.QSize(200, 200))
        self.pushButton_30.setObjectName("pushButton_30")
        self.label_58 = QtWidgets.QLabel(self.Home)
        self.label_58.setGeometry(QtCore.QRect(-60, 0, 1321, 871))
        self.label_58.setStyleSheet("")
        self.label_58.setObjectName("label_58")
        self.label_15 = QtWidgets.QLabel(self.Home)
        self.label_15.setGeometry(QtCore.QRect(210, 380, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Home)
        self.label_16.setGeometry(QtCore.QRect(530, 380, 211, 41))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.Home)
        self.label_17.setGeometry(QtCore.QRect(850, 380, 211, 41))
        self.label_17.setObjectName("label_17")
        self.label_58.raise_()
        self.pushButton_23.raise_()
        self.pushButton_26.raise_()
        self.pushButton_27.raise_()
        self.pushButton_29.raise_()
        self.pushButton_30.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.stackedWidget.addWidget(self.Home)
        self.Druga_analiza = QtWidgets.QWidget()
        self.Druga_analiza.setObjectName("Druga_analiza")
        self.label_69 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_69.setGeometry(QtCore.QRect(250, 410, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_24.setGeometry(QtCore.QRect(250, 630, 81, 31))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_74 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_74.setGeometry(QtCore.QRect(340, 490, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_25.setGeometry(QtCore.QRect(340, 630, 81, 31))
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_26.setGeometry(QtCore.QRect(20, 510, 91, 31))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_27.setGeometry(QtCore.QRect(250, 430, 81, 31))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_82 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_82.setGeometry(QtCore.QRect(140, 610, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.label_84 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_84.setGeometry(QtCore.QRect(420, 830, 55, 16))
        self.label_84.setText("")
        self.label_84.setObjectName("label_84")
        self.label_86 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_86.setGeometry(QtCore.QRect(250, 550, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.label_88 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_88.setGeometry(QtCore.QRect(20, 330, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_88.setFont(font)
        self.label_88.setObjectName("label_88")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_28.setGeometry(QtCore.QRect(340, 570, 81, 31))
        self.lineEdit_28.setText("")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_91 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_91.setGeometry(QtCore.QRect(140, 550, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.label_93 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_93.setGeometry(QtCore.QRect(340, 410, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_94.setGeometry(QtCore.QRect(20, 550, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_94.setFont(font)
        self.label_94.setObjectName("label_94")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_33.setGeometry(QtCore.QRect(20, 570, 91, 31))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.label_103 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_103.setGeometry(QtCore.QRect(20, 400, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_103.setFont(font)
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_104.setGeometry(QtCore.QRect(420, 850, 55, 16))
        self.label_104.setText("")
        self.label_104.setObjectName("label_104")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_34.setGeometry(QtCore.QRect(340, 510, 81, 31))
        self.lineEdit_34.setText("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_107 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_107.setGeometry(QtCore.QRect(250, 370, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_107.setFont(font)
        self.label_107.setObjectName("label_107")
        self.label_111 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_111.setGeometry(QtCore.QRect(250, 610, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_35.setGeometry(QtCore.QRect(250, 510, 81, 31))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.pushButton_2 = QtWidgets.QPushButton(self.Druga_analiza)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_31 = QtWidgets.QPushButton(self.Druga_analiza)
        self.pushButton_31.setGeometry(QtCore.QRect(860, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName("pushButton_31")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Druga_analiza)
        self.tabWidget_2.setGeometry(QtCore.QRect(430, 190, 831, 661))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWebEngineWidgets.QWebEngineView()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWebEngineWidgets.QWebEngineView()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.pushButton_32 = QtWidgets.QPushButton(self.Druga_analiza)
        self.pushButton_32.setGeometry(QtCore.QRect(380, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setObjectName("pushButton_32")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.Druga_analiza)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 60, 1231, 121))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_123 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_123.setGeometry(QtCore.QRect(250, 490, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_123.setFont(font)
        self.label_123.setObjectName("label_123")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_39.setGeometry(QtCore.QRect(140, 630, 91, 31))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_40.setGeometry(QtCore.QRect(140, 570, 91, 31))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_127 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_127.setGeometry(QtCore.QRect(340, 550, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_127.setFont(font)
        self.label_127.setObjectName("label_127")
        self.label_128 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_128.setGeometry(QtCore.QRect(20, 490, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_128.setFont(font)
        self.label_128.setObjectName("label_128")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_41.setGeometry(QtCore.QRect(20, 430, 211, 31))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.label_129 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_129.setGeometry(QtCore.QRect(340, 610, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_129.setFont(font)
        self.label_129.setObjectName("label_129")
        self.pushButton_34 = QtWidgets.QPushButton(self.Druga_analiza)
        self.pushButton_34.setGeometry(QtCore.QRect(20, 710, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setObjectName("pushButton_34")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_44.setGeometry(QtCore.QRect(250, 570, 81, 31))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_46.setGeometry(QtCore.QRect(340, 430, 81, 31))
        self.lineEdit_46.setText("")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.pushButton_37 = QtWidgets.QPushButton(self.Druga_analiza)
        self.pushButton_37.setGeometry(QtCore.QRect(20, 770, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setObjectName("pushButton_37")
        self.label_135 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_135.setGeometry(QtCore.QRect(140, 490, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_135.setFont(font)
        self.label_135.setObjectName("label_135")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_47.setGeometry(QtCore.QRect(140, 510, 91, 31))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.pushButton_38 = QtWidgets.QPushButton(self.Druga_analiza)
        self.pushButton_38.setGeometry(QtCore.QRect(250, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet("")
        self.pushButton_38.setObjectName("pushButton_38")
        self.lineEdit_63 = QtWidgets.QLineEdit(self.Druga_analiza)
        self.lineEdit_63.setGeometry(QtCore.QRect(20, 630, 91, 31))
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.label_195 = QtWidgets.QLabel(self.Druga_analiza)
        self.label_195.setGeometry(QtCore.QRect(20, 610, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_195.setFont(font)
        self.label_195.setObjectName("label_195")
        self.pushButton_15 = QtWidgets.QPushButton(self.Druga_analiza)
        self.pushButton_15.setGeometry(QtCore.QRect(1120, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_18 = QtWidgets.QPushButton(self.Druga_analiza)
        self.pushButton_18.setGeometry(QtCore.QRect(990, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.stackedWidget.addWidget(self.Druga_analiza)
        self.Treca_analiza = QtWidgets.QWidget()
        self.Treca_analiza.setObjectName("Treca_analiza")
        self.label_78 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_78.setGeometry(QtCore.QRect(240, 440, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_95 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_95.setGeometry(QtCore.QRect(240, 380, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_95.setFont(font)
        self.label_95.setObjectName("label_95")
        self.pushButton_13 = QtWidgets.QPushButton(self.Treca_analiza)
        self.pushButton_13.setGeometry(QtCore.QRect(1000, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_99 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_99.setGeometry(QtCore.QRect(110, 660, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.label_110 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_110.setGeometry(QtCore.QRect(340, 500, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_110.setFont(font)
        self.label_110.setObjectName("label_110")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_31.setGeometry(QtCore.QRect(10, 520, 91, 31))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_138 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_138.setGeometry(QtCore.QRect(240, 320, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_138.setFont(font)
        self.label_138.setObjectName("label_138")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_32.setGeometry(QtCore.QRect(240, 460, 91, 31))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.label_142 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_142.setGeometry(QtCore.QRect(110, 550, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_142.setFont(font)
        self.label_142.setObjectName("label_142")
        self.label_143 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_143.setGeometry(QtCore.QRect(290, 870, 55, 16))
        self.label_143.setText("")
        self.label_143.setObjectName("label_143")
        self.label_146 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_146.setGeometry(QtCore.QRect(110, 440, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.label_148 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_148.setGeometry(QtCore.QRect(10, 280, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_148.setFont(font)
        self.label_148.setObjectName("label_148")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_37.setGeometry(QtCore.QRect(10, 460, 91, 31))
        self.lineEdit_37.setText("")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.pushButton_14 = QtWidgets.QPushButton(self.Treca_analiza)
        self.pushButton_14.setGeometry(QtCore.QRect(1130, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_150 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_150.setGeometry(QtCore.QRect(10, 660, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_150.setFont(font)
        self.label_150.setObjectName("label_150")
        self.label_151 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_151.setGeometry(QtCore.QRect(110, 500, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_151.setFont(font)
        self.label_151.setObjectName("label_151")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_42.setGeometry(QtCore.QRect(240, 340, 91, 31))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.label_153 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_153.setGeometry(QtCore.QRect(340, 440, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_153.setFont(font)
        self.label_153.setObjectName("label_153")
        self.label_154 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_154.setGeometry(QtCore.QRect(10, 550, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_154.setFont(font)
        self.label_154.setObjectName("label_154")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_45.setGeometry(QtCore.QRect(10, 400, 91, 31))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.label_155 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_155.setGeometry(QtCore.QRect(110, 380, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_155.setFont(font)
        self.label_155.setObjectName("label_155")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_48.setGeometry(QtCore.QRect(110, 400, 91, 31))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_49.setGeometry(QtCore.QRect(10, 570, 91, 31))
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.label_163 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_163.setGeometry(QtCore.QRect(10, 310, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_163.setFont(font)
        self.label_163.setObjectName("label_163")
        self.label_165 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_165.setGeometry(QtCore.QRect(340, 320, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_165.setFont(font)
        self.label_165.setObjectName("label_165")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_50.setGeometry(QtCore.QRect(340, 520, 91, 31))
        self.lineEdit_50.setText("")
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.label_168 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_168.setGeometry(QtCore.QRect(10, 380, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_168.setFont(font)
        self.label_168.setObjectName("label_168")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_51.setGeometry(QtCore.QRect(240, 520, 91, 31))
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_52.setGeometry(QtCore.QRect(110, 680, 91, 31))
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.pushButton_16 = QtWidgets.QPushButton(self.Treca_analiza)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_53.setGeometry(QtCore.QRect(340, 340, 91, 31))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.pushButton_17 = QtWidgets.QPushButton(self.Treca_analiza)
        self.pushButton_17.setGeometry(QtCore.QRect(870, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.Treca_analiza)
        self.tabWidget_3.setGeometry(QtCore.QRect(440, 220, 851, 631))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWebEngineWidgets.QWebEngineView()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWebEngineWidgets.QWebEngineView()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWebEngineWidgets.QWebEngineView()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QtWebEngineWidgets.QWebEngineView()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_13 = QtWebEngineWidgets.QWebEngineView()
        self.tab_13.setObjectName("tab_13")
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_12 = QtWebEngineWidgets.QWebEngineView()
        self.tab_12.setObjectName("tab_12")
        self.tabWidget_3.addTab(self.tab_12, "")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.Treca_analiza)
        self.textBrowser_3.setGeometry(QtCore.QRect(30, 50, 1231, 161))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_183 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_183.setGeometry(QtCore.QRect(240, 500, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_183.setFont(font)
        self.label_183.setObjectName("label_183")
        self.label_185 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_185.setGeometry(QtCore.QRect(110, 320, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_185.setFont(font)
        self.label_185.setObjectName("label_185")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_55.setGeometry(QtCore.QRect(110, 570, 91, 31))
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_56.setGeometry(QtCore.QRect(110, 520, 91, 31))
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.label_187 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_187.setGeometry(QtCore.QRect(10, 440, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_187.setFont(font)
        self.label_187.setObjectName("label_187")
        self.label_188 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_188.setGeometry(QtCore.QRect(10, 500, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_188.setFont(font)
        self.label_188.setObjectName("label_188")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_57.setGeometry(QtCore.QRect(10, 340, 91, 31))
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_58.setGeometry(QtCore.QRect(110, 340, 91, 31))
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.pushButton_21 = QtWidgets.QPushButton(self.Treca_analiza)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 720, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_59.setGeometry(QtCore.QRect(10, 680, 91, 31))
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_60.setGeometry(QtCore.QRect(110, 460, 91, 31))
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.lineEdit_61 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_61.setGeometry(QtCore.QRect(240, 400, 91, 31))
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.lineEdit_62 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_62.setGeometry(QtCore.QRect(340, 460, 91, 31))
        self.lineEdit_62.setText("")
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.pushButton_24 = QtWidgets.QPushButton(self.Treca_analiza)
        self.pushButton_24.setGeometry(QtCore.QRect(360, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.Treca_analiza)
        self.pushButton_25.setGeometry(QtCore.QRect(10, 780, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_33 = QtWidgets.QPushButton(self.Treca_analiza)
        self.pushButton_33.setGeometry(QtCore.QRect(230, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setObjectName("pushButton_33")
        self.label_125 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_125.setGeometry(QtCore.QRect(340, 600, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_125.setFont(font)
        self.label_125.setObjectName("label_125")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_54.setGeometry(QtCore.QRect(240, 620, 91, 31))
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.label_184 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_184.setGeometry(QtCore.QRect(240, 600, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_184.setFont(font)
        self.label_184.setObjectName("label_184")
        self.lineEdit_64 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_64.setGeometry(QtCore.QRect(340, 620, 91, 31))
        self.lineEdit_64.setText("")
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.label_186 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_186.setGeometry(QtCore.QRect(240, 570, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_186.setFont(font)
        self.label_186.setObjectName("label_186")
        self.label_189 = QtWidgets.QLabel(self.Treca_analiza)
        self.label_189.setGeometry(QtCore.QRect(240, 660, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_189.setFont(font)
        self.label_189.setObjectName("label_189")
        self.lineEdit_65 = QtWidgets.QLineEdit(self.Treca_analiza)
        self.lineEdit_65.setGeometry(QtCore.QRect(240, 680, 91, 31))
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.label_78.raise_()
        self.label_95.raise_()
        self.pushButton_13.raise_()
        self.label_99.raise_()
        self.label_110.raise_()
        self.lineEdit_31.raise_()
        self.label_138.raise_()
        self.lineEdit_32.raise_()
        self.label_142.raise_()
        self.label_143.raise_()
        self.label_146.raise_()
        self.label_148.raise_()
        self.lineEdit_37.raise_()
        self.pushButton_14.raise_()
        self.label_150.raise_()
        self.label_151.raise_()
        self.lineEdit_42.raise_()
        self.label_153.raise_()
        self.label_154.raise_()
        self.lineEdit_45.raise_()
        self.label_155.raise_()
        self.lineEdit_48.raise_()
        self.lineEdit_49.raise_()
        self.label_163.raise_()
        self.label_165.raise_()
        self.lineEdit_50.raise_()
        self.label_168.raise_()
        self.lineEdit_51.raise_()
        self.lineEdit_52.raise_()
        self.pushButton_16.raise_()
        self.lineEdit_53.raise_()
        self.pushButton_17.raise_()
        self.tabWidget_3.raise_()
        self.label_183.raise_()
        self.label_185.raise_()
        self.lineEdit_55.raise_()
        self.lineEdit_56.raise_()
        self.label_187.raise_()
        self.label_188.raise_()
        self.lineEdit_57.raise_()
        self.lineEdit_58.raise_()
        self.pushButton_21.raise_()
        self.lineEdit_59.raise_()
        self.lineEdit_60.raise_()
        self.lineEdit_61.raise_()
        self.lineEdit_62.raise_()
        self.pushButton_24.raise_()
        self.pushButton_25.raise_()
        self.pushButton_33.raise_()
        self.textBrowser_3.raise_()
        self.label_125.raise_()
        self.lineEdit_54.raise_()
        self.label_184.raise_()
        self.lineEdit_64.raise_()
        self.label_186.raise_()
        self.label_189.raise_()
        self.lineEdit_65.raise_()
        self.stackedWidget.addWidget(self.Treca_analiza)
        self.Pomoc = QtWidgets.QWidget()
        self.Pomoc.setObjectName("Pomoc")
        self.pushButton_28 = QtWidgets.QPushButton(self.Pomoc)
        self.pushButton_28.setGeometry(QtCore.QRect(1094, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_35 = QtWidgets.QPushButton(self.Pomoc)
        self.pushButton_35.setGeometry(QtCore.QRect(320, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.Pomoc)
        self.pushButton_36.setGeometry(QtCore.QRect(440, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_39 = QtWidgets.QPushButton(self.Pomoc)
        self.pushButton_39.setGeometry(QtCore.QRect(40, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_79 = QtWidgets.QPushButton(self.Pomoc)
        self.pushButton_79.setGeometry(QtCore.QRect(200, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_79.setFont(font)
        self.pushButton_79.setObjectName("pushButton_79")
        self.textEdit = QtWidgets.QTextEdit(self.Pomoc)
        self.textEdit.setGeometry(QtCore.QRect(90, 210, 1041, 651))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_41 = QtWidgets.QPushButton(self.Pomoc)
        self.pushButton_41.setGeometry(QtCore.QRect(720, 80, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setObjectName("pushButton_41")
        self.label_8 = QtWidgets.QLabel(self.Pomoc)
        self.label_8.setGeometry(QtCore.QRect(90, 130, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.Pomoc)
        self.Pomoc_f = QtWidgets.QWidget()
        self.Pomoc_f.setObjectName("Pomoc_f")
        self.pushButton_40 = QtWidgets.QPushButton(self.Pomoc_f)
        self.pushButton_40.setGeometry(QtCore.QRect(1110, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_42 = QtWidgets.QPushButton(self.Pomoc_f)
        self.pushButton_42.setGeometry(QtCore.QRect(450, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setObjectName("pushButton_42")
        self.textEdit_2 = QtWidgets.QTextEdit(self.Pomoc_f)
        self.textEdit_2.setGeometry(QtCore.QRect(140, 210, 911, 651))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_43 = QtWidgets.QPushButton(self.Pomoc_f)
        self.pushButton_43.setGeometry(QtCore.QRect(720, 80, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_80 = QtWidgets.QPushButton(self.Pomoc_f)
        self.pushButton_80.setGeometry(QtCore.QRect(320, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_80.setFont(font)
        self.pushButton_80.setObjectName("pushButton_80")
        self.pushButton_44 = QtWidgets.QPushButton(self.Pomoc_f)
        self.pushButton_44.setGeometry(QtCore.QRect(580, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(self.Pomoc_f)
        self.pushButton_45.setGeometry(QtCore.QRect(140, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setObjectName("pushButton_45")
        self.label_14 = QtWidgets.QLabel(self.Pomoc_f)
        self.label_14.setGeometry(QtCore.QRect(140, 150, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.Pomoc_f)
        self.Oprogramu = QtWidgets.QWidget()
        self.Oprogramu.setObjectName("Oprogramu")
        self.pushButton_8 = QtWidgets.QPushButton(self.Oprogramu)
        self.pushButton_8.setGeometry(QtCore.QRect(1100, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.Oprogramu)
        self.pushButton_10.setGeometry(QtCore.QRect(430, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.Oprogramu)
        self.pushButton_11.setGeometry(QtCore.QRect(560, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_20 = QtWidgets.QPushButton(self.Oprogramu)
        self.pushButton_20.setGeometry(QtCore.QRect(50, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_19 = QtWidgets.QPushButton(self.Oprogramu)
        self.pushButton_19.setGeometry(QtCore.QRect(300, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.Oprogramu)
        self.textBrowser_4.setGeometry(QtCore.QRect(300, 70, 711, 791))
        self.textBrowser_4.setStyleSheet("background : transparent;")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.stackedWidget.addWidget(self.Oprogramu)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Temperaturna polja"))
        self.pushButton.setText(_translate("MainWindow", "Home"))
        self.pushButton_6.setText(_translate("MainWindow", "Pomoć"))
        self.pushButton_3.setText(_translate("MainWindow", "Druga analiza"))
        self.pushButton_9.setText(_translate("MainWindow", "PDF export"))
        self.pushButton_4.setText(_translate("MainWindow", "Treća analiza"))
        self.pushButton_12.setText(_translate("MainWindow", "O programu"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Po površini polubeskonačnog tijela, giba se točkasti toplinski izvor brzinom <span style=\" font-size:10pt; font-weight:600;\">v</span> [m/s]. Snaga (izdašnost) toplinskog izvora je <span style=\" font-size:10pt; font-weight:600;\">q</span> [W]. Koeficijent temperaturne vodljivosti krutine je <span style=\" font-size:10pt; font-weight:600;\">a</span> [m²/s], a toplinska provodnost materijala je <span style=\" font-size:10pt; font-weight:600;\">la</span> [W/(m⋅K)].</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Potrebno je odrediti kvazistacionarno temperaturno polje (pri z = Z1 [m] i z = Z2 [m]) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a)u obliku ϑ = f (x,y) s parametarskom vrijednošću koordinate x</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">b)u obliku ϑ = f (x,y) s parametarskom vrijednošću koordinate y</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">c)u obliku ϑ = f(x,v) s parametarskom vrijednošću brzine v gibanja točkastog toplinskog izvora (v = ±50 % zadane vrijednosti)</p></body></html>"))
        self.label_67.setText(_translate("MainWindow", "Rezolucija Y"))
        self.label_6.setText(_translate("MainWindow", "Donji Y [m]"))
        self.label_11.setText(_translate("MainWindow", "v [m/s]"))
        self.label_30.setText(_translate("MainWindow", "Parametri (2D):"))
        self.label_32.setText(_translate("MainWindow", "v0 [m/s]"))
        self.label_36.setText(_translate("MainWindow", "Y2[m]"))
        self.label_35.setText(_translate("MainWindow", "v1 [m/s]"))
        self.label_7.setText(_translate("MainWindow", "Rezolucija X"))
        self.label_13.setText(_translate("MainWindow", "la [w/(mK)]"))
        self.label_2.setText(_translate("MainWindow", "Gornji Y [m]"))
        self.label_4.setText(_translate("MainWindow", "Granice (3D):"))
        self.label_34.setText(_translate("MainWindow", "Z2 [m]"))
        self.label_37.setText(_translate("MainWindow", "Y3[m]"))
        self.pushButton_7.setText(_translate("MainWindow", "Pokazni primjer"))
        self.label_10.setText(_translate("MainWindow", "a [m²/s]"))
        self.label_31.setText(_translate("MainWindow", "Y1[m]"))
        self.label_38.setText(_translate("MainWindow", "Y4[m]"))
        self.label_39.setText(_translate("MainWindow", "X4[m]"))
        self.label.setText(_translate("MainWindow", "Gornji X [m]"))
        self.label_41.setText(_translate("MainWindow", "X1[m]"))
        self.label_5.setText(_translate("MainWindow", "Donji X [m]"))
        self.label_12.setText(_translate("MainWindow", "Ulazni podaci:"))
        self.pushButton_5.setText(_translate("MainWindow", "Unesi podatke"))
        self.label_33.setText(_translate("MainWindow", "Temperatura taljenja [°C]"))
        self.label_40.setText(_translate("MainWindow", "X3[m]"))
        self.label_42.setText(_translate("MainWindow", "X2[m]"))
        self.label_9.setText(_translate("MainWindow", "q [w]"))
        self.label_3.setText(_translate("MainWindow", "Z1 [m]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "2D-X,T,par:Y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "2D-Y,T,par:X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "2D-X,T,par:v"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "3D-X,Y,T za Z1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "3D-X,Y,T za Z2"))
        self.pushButton_26.setText(_translate("MainWindow", "O programu"))
        self.pushButton_27.setText(_translate("MainWindow", "Pomoć"))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/background/poza.jpg\"/></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans MS\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:600; color:#ffffff;\">Točkasti izvor </span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Linijski izvor</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Plošni izvor</span></p></body></html>"))
        self.label_69.setText(_translate("MainWindow", "X1[m]"))
        self.label_74.setText(_translate("MainWindow", "X4[m]"))
        self.label_82.setText(_translate("MainWindow", "la [w/(mK)]"))
        self.label_86.setText(_translate("MainWindow", "Y1[m]"))
        self.label_88.setText(_translate("MainWindow", "Ulazni podaci:"))
        self.label_91.setText(_translate("MainWindow", "q [w]"))
        self.label_93.setText(_translate("MainWindow", "X2[m]"))
        self.label_94.setText(_translate("MainWindow", "pc [JI/(m³K)]"))
        self.label_103.setText(_translate("MainWindow", "Temperatura taljenja [°C]"))
        self.label_107.setText(_translate("MainWindow", "Parametri (2D):"))
        self.label_111.setText(_translate("MainWindow", "Y3[m]"))
        self.pushButton_2.setText(_translate("MainWindow", "Home"))
        self.pushButton_31.setText(_translate("MainWindow", "PDF export"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "2D-X,T,par:Y"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "2D-Y,T,par:X"))
        self.pushButton_32.setText(_translate("MainWindow", "Treća analiza"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Po površini tankog beskonačnog lima (<span style=\" font-size:10pt; font-weight:600;\">6 </span><span style=\" font-size:8pt;\">[m]</span>) giba se linijski toplinski izvor brzinom <span style=\" font-size:10pt; font-weight:600;\">v</span> [m/s]. Snaga (izdašnost) toplinskog izvora je <span style=\" font-size:10pt; font-weight:600;\">q</span> [W]. Toplinska provodnost materijala je <span style=\" font-size:10pt; font-weight:600;\">la</span> [W/(mK)], a umnožak <span style=\" font-size:10pt; font-weight:600;\">pc </span><span style=\" font-size:8pt;\">[</span>JI/(m³K)]. Koeficijent prijelaza topline na okoliš je <span style=\" font-size:10pt; font-weight:600;\">a</span> [W/(m²K)].</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Potrebno je odrediti kvazistacionarno temperaturno polje</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a) u obliku 9 = f (x,y) s parametarskom vrijednošću koordinate x</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">b) u obliku 9 = f (x,y) s parametarskom vrijednošću koordinate y</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_123.setText(_translate("MainWindow", "X3[m]"))
        self.label_127.setText(_translate("MainWindow", "Y2[m]"))
        self.label_128.setText(_translate("MainWindow", "v [m/s]"))
        self.label_129.setText(_translate("MainWindow", "Y4[m]"))
        self.pushButton_34.setText(_translate("MainWindow", "Pokazni primjer"))
        self.pushButton_37.setText(_translate("MainWindow", "Unesi podatke"))
        self.label_135.setText(_translate("MainWindow", "d [m]"))
        self.pushButton_38.setText(_translate("MainWindow", "Prva analiza"))
        self.label_195.setText(_translate("MainWindow", "a [w/(m²K)]"))
        self.pushButton_15.setText(_translate("MainWindow", "O programu"))
        self.pushButton_18.setText(_translate("MainWindow", "Pomoć"))
        self.label_78.setText(_translate("MainWindow", "Thl1[°C]"))
        self.label_95.setText(_translate("MainWindow", "y03[m]"))
        self.pushButton_13.setText(_translate("MainWindow", "Pomoć"))
        self.label_99.setText(_translate("MainWindow", "Rezolucija Y"))
        self.label_110.setText(_translate("MainWindow", "Thl4[°C]"))
        self.label_138.setText(_translate("MainWindow", "y01[m]"))
        self.label_142.setText(_translate("MainWindow", "T04[°C]"))
        self.label_146.setText(_translate("MainWindow", "To[°C]"))
        self.label_148.setText(_translate("MainWindow", "Ulazni podaci:"))
        self.pushButton_14.setText(_translate("MainWindow", "O programu"))
        self.label_150.setText(_translate("MainWindow", "Rezolucija X"))
        self.label_151.setText(_translate("MainWindow", "T02[°C]"))
        self.label_153.setText(_translate("MainWindow", "Thl2[°C]"))
        self.label_154.setText(_translate("MainWindow", "T03[°C]"))
        self.label_155.setText(_translate("MainWindow", "v[m/s]"))
        self.label_163.setText(_translate("MainWindow", "d[m]"))
        self.label_165.setText(_translate("MainWindow", "y02[m]"))
        self.label_168.setText(_translate("MainWindow", "eta"))
        self.pushButton_16.setText(_translate("MainWindow", "Home"))
        self.pushButton_17.setText(_translate("MainWindow", "PDF export"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Temp-cik"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "V_hl"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "tas"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MainWindow", "t85/E graf"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("MainWindow", "Tmax"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("MainWindow", "Širina ZUT"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Dva lima iz niskolegiranog čelika, debljine d [m], zavaruju se sučeono, jednostrano, u jednom prolazu, na</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">podlošci od keramike, sljedećim parametrima U=28 [V], I=120 [A], eta=0,8, v=4 [m/s].</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Odrediti:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">1. Temperaturni ciklus točaka koje se nalaze y01[m], y02[m], y03[m] od osi zavara uz T= T01[°C], T02[°C], T03[°C],T04[°C]</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2. Trenutnu brzinu hlađenja točke pri temperaturama Thl1[°C], Thl2[°C], Thl3[°C] i Thl4[°C] uz temperaturu To=20°C</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">3. Vrijeme hlađenja tas</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">4. Maksimalnu temperaturu koju dostižu točke (y01[m], y02[m],  y03[m]) zavarenog spoja</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">5. Širinu zone utjecaja topline</span></p></body></html>"))
        self.label_183.setText(_translate("MainWindow", "Thl3[°C]"))
        self.label_185.setText(_translate("MainWindow", "U[V]"))
        self.label_187.setText(_translate("MainWindow", "I[A]"))
        self.label_188.setText(_translate("MainWindow", "T01[°C]"))
        self.pushButton_21.setText(_translate("MainWindow", "Pokazni primjer"))
        self.pushButton_24.setText(_translate("MainWindow", "Druga analiza"))
        self.pushButton_25.setText(_translate("MainWindow", "Unesi podatke"))
        self.pushButton_33.setText(_translate("MainWindow", "Prva analiza"))
        self.label_125.setText(_translate("MainWindow", "Cp[J/(kgK]"))
        self.label_184.setText(_translate("MainWindow", "rho[kg/m³]"))
        self.label_186.setText(_translate("MainWindow", "Podaci o materijalu:"))
        self.label_189.setText(_translate("MainWindow", "lambda[W/mK]"))
        self.pushButton_28.setText(_translate("MainWindow", "O programu"))
        self.pushButton_35.setText(_translate("MainWindow", "Druga analiza"))
        self.pushButton_36.setText(_translate("MainWindow", "Treća analiza"))
        self.pushButton_39.setText(_translate("MainWindow", "Home"))
        self.pushButton_79.setText(_translate("MainWindow", "Prva analiza"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/slike/pomoc_merged.png\" /></p></body></html>"))
        self.pushButton_41.setText(_translate("MainWindow", "Korištene formule"))
        self.label_8.setText(_translate("MainWindow", "Upute za korištenje programa:"))
        self.pushButton_40.setText(_translate("MainWindow", "O programu"))
        self.pushButton_42.setText(_translate("MainWindow", "Druga analiza"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/upute_f/pomoc_formule_merged.png\" /></p></body></html>"))
        self.pushButton_43.setText(_translate("MainWindow", "Upute za korištenje programa:"))
        self.pushButton_80.setText(_translate("MainWindow", "Prva analiza"))
        self.pushButton_44.setText(_translate("MainWindow", "Treća analiza"))
        self.pushButton_45.setText(_translate("MainWindow", "Home"))
        self.label_14.setText(_translate("MainWindow", "Korištene formule:"))
        self.pushButton_8.setText(_translate("MainWindow", "Pomoć"))
        self.pushButton_10.setText(_translate("MainWindow", "Druga analiza"))
        self.pushButton_11.setText(_translate("MainWindow", "Treća analiza"))
        self.pushButton_20.setText(_translate("MainWindow", "Home"))
        self.pushButton_19.setText(_translate("MainWindow", "Prva analiza"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">Program je rađen kao diplomski rad iz kolegija &quot;Temperaturna polja&quot;. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">Programski jezik korišten za izradu programa je Python 3.8.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:8pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">Vanjski moduli korištemi za izradu programa:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">-PyQt5 </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">-numpy</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">-plotly</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">-pandas</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">-fpdf-</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">scipy-</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">-sys</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">-subprocess</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">-os</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">-airium</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">Autor: Ivor Šantak</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">Mentor diplomskog rada: doc.dr.sc. Mario Holik</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">Program je izrađen 2022. godine</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">Pozadinska fotografija: Greg Rosenke, Shutterstock</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\'; font-size:12pt;\">Formule: prof.dr.sc. Marija Živić, predavanja iz kolegija &quot;Temperaturna polja&quot;</span></p></body></html>"))
from PyQt5 import QtWebEngineWidgets
import test2
import test3
import test4
import test5
import test_pozadina
import test
import test_upute1
